#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qualified_Contractor_Tracking
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="contractors")]
	public partial class ExpiringInsuranceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ExpiringInsuranceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["contractorsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExpiringInsuranceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpiringInsuranceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpiringInsuranceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpiringInsuranceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ExpiringInsurancePolicy> ExpiringInsurancePolicies
		{
			get
			{
				return this.GetTable<ExpiringInsurancePolicy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExpiringInsurancePolicies")]
	public partial class ExpiringInsurancePolicy
	{
		
		private string _Company;
		
		private int _cID;
		
		private string _Type;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private string _CertReqFor;
		
		private string _Name;
		
		private string _InsuranceCompanyEmail;
		
		private string _InsuranceBroker;
		
		private string _InsuranceBrokerEmail;
		
		private System.Nullable<int> _BrokerEmailID;
		
		private System.Nullable<int> _Count;
		
		public ExpiringInsurancePolicy()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cID", DbType="Int NOT NULL")]
		public int cID
		{
			get
			{
				return this._cID;
			}
			set
			{
				if ((this._cID != value))
				{
					this._cID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(25)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="Date")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this._ExpiryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertReqFor", DbType="NVarChar(255)")]
		public string CertReqFor
		{
			get
			{
				return this._CertReqFor;
			}
			set
			{
				if ((this._CertReqFor != value))
				{
					this._CertReqFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceCompanyEmail", DbType="NVarChar(50)")]
		public string InsuranceCompanyEmail
		{
			get
			{
				return this._InsuranceCompanyEmail;
			}
			set
			{
				if ((this._InsuranceCompanyEmail != value))
				{
					this._InsuranceCompanyEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceBroker", DbType="NVarChar(150)")]
		public string InsuranceBroker
		{
			get
			{
				return this._InsuranceBroker;
			}
			set
			{
				if ((this._InsuranceBroker != value))
				{
					this._InsuranceBroker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceBrokerEmail", DbType="NVarChar(150)")]
		public string InsuranceBrokerEmail
		{
			get
			{
				return this._InsuranceBrokerEmail;
			}
			set
			{
				if ((this._InsuranceBrokerEmail != value))
				{
					this._InsuranceBrokerEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrokerEmailID", DbType="Int")]
		public System.Nullable<int> BrokerEmailID
		{
			get
			{
				return this._BrokerEmailID;
			}
			set
			{
				if ((this._BrokerEmailID != value))
				{
					this._BrokerEmailID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", DbType="Int")]
		public System.Nullable<int> Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this._Count = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
