<?xml version="1.0" encoding="utf-8"?><Database Name="contractors" Class="CLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=contractors;User ID=contractor" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="contractorsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.lookupTypeOfPolicy" Member="lookupTypeOfPolicies">
    <Type Name="lookupTypeOfPolicy">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportBrokerInfo" Member="ReportBrokerInfos">
    <Type Name="ReportBrokerInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BrokerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BrokerAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BrokerEmail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TypeOfPolicy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportAODA" Member="ReportAODAs">
    <Type Name="ReportAODA">
      <Column Name="ID" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MailingAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AODAFormSubmit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>